-- INVIS CORE - SUPABASE DDL FULL MIGRATION SCRIPT
-- Execute nas consultas SQL do painel do Supabase.

-- 1. Tabela de Perfis
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text UNIQUE NOT NULL,
  full_name text,
  nickname text UNIQUE,
  phone text,
  birth_date text,
  age integer,
  tier text DEFAULT 'FREE',
  wallet_ic_gold numeric DEFAULT 5000.0,
  wallet_ic_silver numeric DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabela de Tarefas
CREATE TABLE IF NOT EXISTS public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  text text NOT NULL,
  completed boolean DEFAULT false,
  priority text DEFAULT 'none',
  reminder_time text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Mensagens Globais (Social/Fórum)
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  sender text NOT NULL,
  avatar text,
  text text,
  lang text DEFAULT 'pt-BR',
  audio_duration text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabela de Transações
CREATE TABLE IF NOT EXISTS public.transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  type text NOT NULL,
  amount numeric NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabela de Inventário
CREATE TABLE IF NOT EXISTS public.inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  item_id text NOT NULL,
  title text NOT NULL,
  type text NOT NULL,
  is_stamped boolean DEFAULT false,
  is_used boolean DEFAULT false,
  acquired_at text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- SEGURANÇA E RLS (Row Level Security)

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;

-- Políticas para Profiles
CREATE POLICY "Usuários podem ver seu próprio perfil" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Usuários podem atualizar seu próprio perfil" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Usuários podem inserir seu próprio perfil" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Políticas para Tasks
CREATE POLICY "Usuários gerenciam suas originais tasks" ON public.tasks FOR ALL USING (auth.uid() = user_id);

-- Políticas para Messages (Acesso global de leitura)
CREATE POLICY "Mensagens visíveis globalmente" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Usuários podem inserir mensagens" ON public.messages FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Políticas para Transactions
CREATE POLICY "Usuários veem suas próprias transações" ON public.transactions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Transações são apenas de inserção" ON public.transactions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Políticas para Inventory
CREATE POLICY "Usuários gerenciam próprio inventário" ON public.inventory FOR ALL USING (auth.uid() = user_id);

-- Função para automatizar updated_at profiles
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language plpgsql;

CREATE TRIGGER on_profiles_update
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 6. Tabela de Fontes de Mídia Direta (Própria CDN INVIS)
CREATE TABLE IF NOT EXISTS public.invis_media_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  media_id text NOT NULL, -- ID numérico do filme ou série (ex: "335984")
  media_type text NOT NULL CHECK (media_type IN ('movie', 'serie')),
  season integer DEFAULT NULL, -- Nulo para filmes
  episode integer DEFAULT NULL, -- Nulo para filmes
  stream_url text NOT NULL, -- URL direto da mídia (HLS .m3u8 ou MP4)
  resolution text DEFAULT '1080p',
  audio_languages text[] DEFAULT ARRAY['pt-BR', 'en-US'], -- Lista de áudios disponíveis nessa fonte
  subtitles text[] DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela adicional correspondente ao media_catalog do crawler de indexação
CREATE TABLE IF NOT EXISTS public.media_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_id text NOT NULL, -- ID do filme ou série
  media_type text NOT NULL, -- 'movie' ou 'tv'
  stream_url text NOT NULL,
  resolution text DEFAULT '1080p',
  tracks_data jsonb DEFAULT NULL, -- contém metadados adicionais das faixas
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para Mídia
ALTER TABLE public.invis_media_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_catalog ENABLE ROW LEVEL SECURITY;

-- Política de Leitura Pública Geral para reprodução direta instantânea
CREATE POLICY "Leitura pública de fontes de mídia direta" ON public.invis_media_sources FOR SELECT USING (true);
CREATE POLICY "Leitura pública de catalogo de midia" ON public.media_catalog FOR SELECT USING (true);

-- Política de Gerenciamento exclusivo por perfil Administrativo do sistema INVIS (opcional para painel)
CREATE POLICY "Administradores gerenciam fontes de mídia" ON public.invis_media_sources FOR ALL USING (true);
CREATE POLICY "Administradores gerenciam catalogo de midia" ON public.media_catalog FOR ALL USING (true);

-- Criar índices de busca rápida para evitar lentidão ou buffering por latência de banco
CREATE INDEX IF NOT EXISTS idx_invis_media_id_type ON public.invis_media_sources (media_id, media_type);
CREATE INDEX IF NOT EXISTS idx_invis_media_ep ON public.invis_media_sources (media_id, season, episode) WHERE (media_type = 'serie');
CREATE INDEX IF NOT EXISTS idx_media_catalog_id_type ON public.media_catalog (title_id, media_type);

-- Habilitar Realtime
alter publication supabase_realtime add table public.tasks, public.messages, public.inventory, public.transactions, public.invis_media_sources, public.media_catalog;
